### ISSUE TITLE
Kubernetes - MongooseServerSelectionError: connect ECONNREFUSED

### ISSUE THREAD

**Issue by tamfiteoco** [StephenGrider/ticketing#25]
I try to connect the mongodb in my pod of kubernetes but get the error:

MongooseServerSelectionError: connect ECONNREFUSED

My Pods and Services:

```
NAME                               READY   STATUS    RESTARTS   AGE
auth-depl-5cc58f4f86-22hn6         1/1     Running   0          6m52s
auth-mongo-depl-69cb9cccc7-s8qw7   1/1     Running   0          6m52s
```

```
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
auth-mongo-srv   ClusterIP   10.111.58.252   <none>        27017/TCP   8m12s
auth-srv         ClusterIP   10.102.134.66   <none>        3000/TCP    8m12s
kubernetes       ClusterIP   10.96.0.1       <none>        443/TCP     3d1h
```

My Mongo Deployment file: auth-mongo-depl.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
        - name: auth-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-srv
spec:
  selector:
    app: auth-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
```

My app:

```
const start = async () => {
  try {
    await mongoose.connect('mongodb://auth-mongo-srv:27017/auth');
    console.log('Connected to MongoDb');
  } catch (error) {
    console.error(error);
  }

  app.listen(3000, () => {
    console.log('Listening on port 3000!!!!');
  });
};
```

I got the error when deploying auth-mongo-depl

```
[auth]MongooseServerSelectionError: connect ECONNREFUSED 10.111.58.252:27017
[auth]    at _handleConnectionErrors (/app/node_modules/mongoose/lib/connection.js:829:11)
[auth]    at NativeConnection.openUri (/app/node_modules/mongoose/lib/connection.js:804:11) {
[auth]  reason: TopologyDescription {
[auth]    type: 'Unknown',
[auth]    servers: Map(1) { 'auth-mongo-srv:27017' => [ServerDescription] },
[auth]    stale: false,
[auth]    compatible: true,
[auth]    heartbeatFrequencyMS: 10000,
[auth]    localThresholdMS: 15,
[auth]    setName: null,
[auth]    maxElectionId: null,
[auth]    maxSetVersion: null,
[auth]    commonWireVersion: 0,
[auth]    logicalSessionTimeoutMinutes: null
[auth]  },
```

How can I connect the mongodb in Kubernetes ?
